1-1: Affine Functions with 1 Feature

Code.1-1-1: Affine Function

In [7]:
import tensorflow as tf

from tensorflow.keras.layers import Dense

x = tf.constant([[10.]]) # input setting (Note: INput => Matrix)

dense = Dense(units=1, activation='linear')  # imp. an aiffine function

y_tf = dense(x) # forward propagation + praram initialization

W, B = dense.get_weights()  # get the weight and bias

y_man = tf.linalg.matmul(x, W) + B  # forward propagatin(Manual)

#print result
print("========== Input/Weight/Bias ==========")
print("x: {}\n{}\n".format(x.shape, x.numpy()))
print("W: {}\n{}\n".format(W.shape, W))
print("B: {}\n{}\n".format(B.shape, B))

print("========== Output ==========")
print("y_tf(Tensorflow): {}\n{}\n".format(y_tf.shape, y_tf.numpy()))
print("y_man(Manual): {}\n{}\n".format(y_man.shape, y_man.numpy()))

========== Input/Weight/Bias ==========
x: (1, 1)
[[10.]]

W: (1, 1)
[[-1.5199196]]

B: (1,)
[0.]

========== Output ==========
y_tf(Tensorflow): (1, 1)
[[-15.199196]]

y_man(Manual): (1, 1)
[[-15.199196]]



Code.1-1-2: Parameter Initialization

In [10]:
import tensorflow as tf

from tensorflow.keras.layers import Dense
from tensorflow.keras.initializers import Constant

x = tf.constant([[10.]]) # input setting (Note: INput => Matrix)

# weight /bias initialization
w, b = tf.constant(10,), tf.constant(20,)
w_init, b_init = Constant(w), Constant(b)

print(w_init, b_init)

# imp. an aiffine function
dense = Dense(units=1,
              activation='linear',
              kernel_initializer=w_init,
              bias_initializer=b_init)

y_tf = dense(x)
print(y_tf)
W, B = dense.get_weights()

# print result
print("W: {}\n{}\n".format(W.shape, W))
print("B: {}\n{}\n".format(B.shape, B))

<keras.src.initializers.constant_initializers.Constant object at 0x000001712CE5FB00> <keras.src.initializers.constant_initializers.Constant object at 0x000001712CDB3DA0>
tf.Tensor([[120.]], shape=(1, 1), dtype=float32)
W: (1, 1)
[[10.]]

B: (1,)
[20.]



1-2: Affine Functions with n Features

Code.1-2-1: Affine Function with n Features

In [12]:
import tensorflow as tf

from tensorflow.keras.layers import Dense

x = tf.random.uniform(shape=(1, 10), minval=0, maxval=10)

dense = Dense(units=1)

y_tf = dense(x)

W, B = dense.get_weights()

y_man = tf.linalg.matmul(x, W) + B

print("========== Input/Weight/Bias ==========")
print("x: {}\n{}\n".format(x.shape, x.numpy()))
print("W: {}\n{}\n".format(W.shape, W))
print("B: {}\n{}\n".format(B.shape, B))

print("========== Output ==========")
print("y_tf(Tensorflow): {}\n{}\n".format(y_tf.shape, y_tf.numpy()))
print("y_man(Manual): {}\n{}\n".format(y_man.shape, y_man.numpy()))

========== Input/Weight/Bias ==========
x: (1, 10)
[[5.6903625 1.0447216 0.6050384 6.413083  7.980776  1.9794416 3.789283
  4.6182833 6.1514654 7.2973785]]

W: (10, 1)
[[-0.5202753 ]
 [-0.46457648]
 [-0.02494949]
 [ 0.49540383]
 [ 0.5876029 ]
 [-0.06299889]
 [-0.29903853]
 [ 0.15701813]
 [-0.2793522 ]
 [ 0.724358  ]]

B: (1,)
[0.]

========== Output ==========
y_tf(Tensorflow): (1, 1)
[[7.440389]]

y_man(Manual): (1, 1)
[[7.440389]]



1-3: Activation Functions

Code.1-3-1: Activation Layers

In [5]:
import tensorflow as tf

from tensorflow.keras.layers import Activation
from tensorflow.math import exp, minimum

x = tf.random.normal(shape=(1, 5))

# imp. an aiffine function
sigmoid = Activation('sigmoid')
tanh = Activation('tanh')
relu = Activation('relu')

# forward propagation
y_sigmoid = sigmoid(x)
y_tanh = tanh(x)
y_relu = relu(x)

# forward propagatin(Manual)
y_sigmoid_man = 1 / (1 + exp(-x))
y_tanh_man = (exp(x) - exp(-x)) / (exp(x) +exp(-x))
y_relu_man = minimum(0, x)


print("x: {}\n{}".format(x.shape, x.numpy()))
print("Sigmoid(tensorflow): {}\n{}".format(y_sigmoid.shape, y_sigmoid.numpy()))
print("Sigmoid(Manual): {}\n{}".format(y_sigmoid_man.shape, y_relu_man.numpy()))

print("Tanh(tensorflow): {}\n{}".format(y_tanh.shape, y_tanh.numpy()))
print("Tanh(Manual): {}\n{}".format(y_tanh_man.shape, y_tanh_man.numpy()))

print("ReLU(tensorflow): {}\n{}".format(y_relu.shape, y_relu.numpy()))
print("ReLU(Manual): {}\n{}".format(y_relu_man.shape, y_relu_man.numpy()))

x: (1, 5)
[[ 1.8603033   0.07097753  0.7002994   0.1605336  -0.8535118 ]]
Sigmoid(tensorflow): (1, 5)
[[0.8653323  0.517737   0.66825414 0.54004747 0.2986967 ]]
Sigmoid(Manual): (1, 5)
[[ 0.         0.         0.         0.        -0.8535118]]
Tanh(tensorflow): (1, 5)
[[ 0.9527068   0.07085857  0.60455775  0.15916862 -0.69289964]]
Tanh(Manual): (1, 5)
[[ 0.9527069   0.07085861  0.6045578   0.15916863 -0.6928997 ]]
ReLU(tensorflow): (1, 5)
[[1.8603033  0.07097753 0.7002994  0.1605336  0.        ]]
ReLU(Manual): (1, 5)
[[ 0.         0.         0.         0.        -0.8535118]]


Code.1-3-2: Activation in Dense Layer

In [6]:
import tensorflow as tf

from tensorflow.keras.layers import Dense
from tensorflow.math import exp

x = tf.random.normal(shape=(1, 5))

# imp. an aiffine function
dense_sigmoid = Dense(units=1, activation='sigmoid')
dense_tanh = Dense(units=1, activation='tanh')
dense_relu = Dense(units=1, activation='relu')

# forward propagation(Tensorflow)
y_sigmoid = dense_sigmoid(x)
y_tanh = dense_tanh(x)
y_relu = dense_relu(x)

print("AN with sigmoid: {}\n{}".format(y_sigmoid.shape, y_sigmoid.numpy()))
print("AN with tanh: {}\n{}".format(y_tanh.shape, y_tanh.numpy()))
print("AN with relu: {}\n{}".format(y_relu.shape, y_relu.numpy()))


# forward propagatin(Manual)
print("\n=======================\n")

W, B = dense_sigmoid.get_weights()
z = tf.linalg.matmul(x, W) + B
a = 1 / (1+ exp(-z))
print()
print("AN with sigmoid(Manual): {}\n{}".format(a.shape, a.numpy()))

AN with sigmoid: (1, 1)
[[0.4684459]]
AN with tanh: (1, 1)
[[0.68366677]]
AN with relu: (1, 1)
[[0.2721987]]


1-4: Affine Neurons

Code.1-4-1: Affine Neurons

In [ ]:
import tensorflow as tf

from tensorflow.keras.layers import Dense

