2-1: Dense Layers

Code.2-1-1: Shape of Dense Layers

In [5]:
import tensorflow as tf

from tensorflow.keras.layers import Dense

N, n_feature = 8, 10
x = tf.random.normal(shape=(N, n_feature))

n_neuron = 3
dense = Dense(units=n_neuron, activation='sigmoid')
Y = dense(x)

W, B = dense.get_weights()

print("======= Input/Weight/Bias ========")
print("x: ", x.shape)
print("W: ", W.shape)
print("B: ", B.shape)
print("Y: ", Y.shape)

======= Input/Weight/Bias ========
x:  (8, 10)
W:  (10, 3)
B:  (3,)
Y:  (8, 3)


Code.2-1-2: Output Calculations

In [35]:
import numpy as np
import tensorflow as tf

from tensorflow.math import exp
from tensorflow.linalg import matmul

from tensorflow.keras.layers import Dense

N, n_feature = 4, 10
x = tf.random.normal(shape=(N, n_feature))

n_neuron = 3
dense = Dense(units=n_neuron, activation='sigmoid')
Y_tf = dense(x)

W, B = dense.get_weights()
print("Y(Tensorflow): \n", Y_tf.numpy())

# calculate with matrix multiplication
z = matmul(x, W) + B
Y_man_matmul = 1 / (1 + exp(-z))
print("Y(with matrix multiplication): \n", Y_man_matmul.numpy())

# calculate with dot product
Y_man_vec = np.zeros(shape=(N, n_neuron))
for x_idx in range(N):
    x = X[x_idx]

    for nu_idx in range(n_neuron):
        w, b = W[:, nu_idx], B[nu_idx]

    z = tf.reduce_sum(x * w) + b
    a = 1 / (1 + np.exp(-z))
    Y_man_vec[x_idx, nu_idx] = a

print("Y(with dot product): \n", Y_man_vec)

Y(Tensorflow): 
 [[0.6227197  0.3540123  0.83642465]
 [0.6656204  0.5844965  0.66431904]
 [0.38678843 0.57822806 0.24596138]
 [0.50226665 0.7700345  0.29330742]]
Y(with matrix multiplication): 
 [[0.62271976 0.3540123  0.83642465]
 [0.66562045 0.5844965  0.6643191 ]
 [0.38678843 0.57822806 0.2459614 ]
 [0.50226665 0.7700345  0.29330745]]
Y(with dot product): 
 [[0.         0.         0.55131675]
 [0.         0.         0.59329149]
 [0.         0.         0.64216197]
 [0.         0.         0.16307319]]


2-2: Cascaded Dense Layers

Code.2-2-1: Shape of Cascaded Dense Layers

In [40]:
import tensorflow as tf

from tensorflow.keras.layers import Dense

N, n_feature = 4, 10
x = tf.random.normal(shape=(N, n_feature))

n_neurons = [3, 5]
dense1 = Dense(units=n_neurons[0], activation='sigmoid')
dense2 = Dense(units=n_neurons[1], activation='sigmoid')

# forward propagation
A1 = dense1(x)
Y = dense2(A1)

# get weights/bias
W1, B1 = dense1.get_weights()
W2, B2 = dense2.get_weights()

print("x: {}\n".format(x.shape))

print("W1: {}".format(W1.shape))
print("B1: {}".format(B1.shape))
print("A1: {}\n".format(A1.shape))

print("W2: {}".format(W2.shape))
print("B2: {}".format(B2.shape))
print("Y: {}".format(Y.shape))

x: (4, 10)

W1: (10, 3)
B1: (3,)
A1: (4, 3)

W2: (3, 5)
B2: (5,)
Y: (4, 5)


Code.2-2-2: Dense Layers with Python List

In [48]:
import tensorflow as tf

from tensorflow.keras.layers import Dense

N, n_feature = 4, 10
x = tf.random.normal(shape=(N, n_feature))

n_neurons = [10, 20, 30, 40, 50, 60, 70, 80, 90, 100]

dense_layers = list()

for n_neuron in n_neurons:
    dense = Dense(units=n_neuron, activation='relu')
    dense_layers.append(dense)
print("input: ", x.shape)

for dense_idx, dense in enumerate(dense_layers):
    x = dense(x)
    print("After dense layer", dense_idx + 1)
    print(x.shape, '\n')


input:  (4, 10)
After dense layer 1
(4, 10) 

After dense layer 2
(4, 20) 

After dense layer 3
(4, 30) 

After dense layer 4
(4, 40) 

After dense layer 5
(4, 50) 

After dense layer 6
(4, 60) 

After dense layer 7
(4, 70) 

After dense layer 8
(4, 80) 

After dense layer 9
(4, 90) 

After dense layer 10
(4, 100) 



Code.2-2-3: Output Calculations

In [52]:
import tensorflow as tf

from tensorflow.math import exp
from tensorflow.linalg import matmul

from tensorflow.keras.layers import Dense

N, n_feature = 4, 10
x = tf.random.normal(shape=(N, n_feature))
x_cp = tf.identity(x) # copy of x 주소가 같기 때문에 

n_neurons = [3, 4, 5]

dense_layers = list()

for n_neuron in n_neurons:
    dense = Dense(units=n_neuron, activation='sigmoid')
    dense_layers.append(dense)

# forward propagation(Tensorflow)
W, B = list(), list()
for dense_idx, dense in enumerate(dense_layers):
    x = dense(x)
    w, b = dense.get_weights()

    W.append(w)
    B.append(b)

print("Y(Tensorflow): \n", x.numpy())

# forward propagation(Manual)
for layer_idx in range(len(n_neurons)):
    w, b = W[layer_idx], B[layer_idx]

    x_cp = matmul(x_cp, w) + b
    x_cp = 1 / (1 + exp(-x_cp))

print("Y(Manual): \n", x_cp.numpy())



Y(Tensorflow): 
 [[0.49346226 0.47916508 0.6208754  0.35693967 0.5283681 ]
 [0.51765996 0.46328515 0.63536036 0.3529246  0.50032383]
 [0.5191708  0.46275797 0.638599   0.34819493 0.49942294]
 [0.4994403  0.47436976 0.62868726 0.35156107 0.52153105]]
Y(Manual): 
 [[0.49346226 0.47916508 0.6208754  0.35693967 0.5283681 ]
 [0.51766    0.46328515 0.63536036 0.3529246  0.50032383]
 [0.5191709  0.46275797 0.6385989  0.34819493 0.4994229 ]
 [0.49944034 0.4743697  0.62868726 0.35156104 0.521531  ]]


2-3: Model Implementation

Code.2-3-1: Model Implementation with Sequential Method

In [ ]:
from tensorflow.keras.layers import Dense

from tensorflow.keras.models import Sequential

model = Sequential()
model.add(Dense(units=10, activation='sigmoid'))
model.add(Dense(units=10, activation='relu'))

Code.2-3-2: Model Implementation with Model-subclassing

In [54]:
from tensorflow.keras.layers import Dense

from tensorflow.keras.models import Model

class TestModel(Model):
    def __init__(self):
        super(TestModel, self).__init__()
        self.dense1 = Dense(units=10, activation='sigmoid')
        self.dense2 = Dense(units=10, activation='relu')

model = TestModel()
print(model.dense1)
print(model.dense2)

Code.2-3-3: Forward Propagation of Models

In [56]:
import tensorflow as tf

from tensorflow.keras.layers import Dense

from tensorflow.keras.models import Sequential
from tensorflow.keras.models import Model

x = tf.random.normal(shape=(4, 10))

# sequential method
model = Sequential()
model.add(Dense(units=10, activation='sigmoid'))
model.add(Dense(units=10, activation='relu'))

Y = model(x)


# Model-subclassing
class TestModel(Model):
    def __init__(self):
        super(TestModel, self).__init__()
        self.dense1 = Dense(units=10, activation='sigmoid')
        self.dense2 = Dense(units=10, activation='relu')

    def call(self, x):
        x = self.dense1(x)
        x = self.dense2(x)
        return x

model = TestModel()
Y = model(x)

In [ ]:
class TestModel(Model):
    def __init__(self):
        super(TestModel, self).__init__()

        self.dense_layers = list()
        for n_neuron in self.n_neurons:
            self.dense_layers.append(Dense(units=10, activation='sigmoid'))
        
    def call(self, x):
        for dense in self.dense_layers:
            x = self.dense(x)
        return x

class TestModel(Model):
    def __init__(self, n_neurons):
        super(TestModel, self).__init__()
        self.n_neurons = n_neurons
        
        self.model = Sequential()
        self.model.add(Dense(units=10, activation='sigmoid'))
        self.model.add(Dense(units=10, activation='sigmoid'))

        def call(self, x):
            for dense in self.dense_layers:
                x = self.model(x)
            return x
        
n_neurons = [3, 4, 5]
model = TestModel(n_neurons=n_neurons)

Code.2-3-4: Layers in Models

In [60]:
import tensorflow as tf

from tensorflow.keras.layers import Dense

from tensorflow.keras.models import Sequential

x = tf.random.normal(shape=(4, 10))

model = Sequential()
model.add(Dense(units=10, activation='sigmoid'))
model.add(Dense(units=20, activation='sigmoid'))

Y = model(x)

print(type(model.layers))
print(model.layers)

for layer in model.layers:
    w, b = layer.get_weights()
    print(w.shape, b.shape)

<class 'list'>
[<keras.src.layers.core.dense.Dense object at 0x000001D1A757DFD0>, <keras.src.layers.core.dense.Dense object at 0x000001D1A79959D0>]
(10, 10) (10,)
(10, 20) (20,)


Code.2-3-5: Trainable Variables in Models

In [64]:
import tensorflow as tf

from tensorflow.keras.layers import Dense

from tensorflow.keras.models import Sequential

x = tf.random.normal(shape=(4, 10))

model = Sequential()
model.add(Dense(units=10, activation='sigmoid'))
model.add(Dense(units=20, activation='sigmoid'))

Y = model(x)

print(type(model.trainable_variables))
print(len(model.trainable_variables))

for train_var in model.trainable_variables:
    print(train_var.shape)

<class 'list'>
4
(10, 10)
(10,)
(10, 20)
(20,)
