Numpy

In [2]:
import numpy as np

Numpy ndarray

In [5]:
a = np.array([1, 2, 3])
print(a, type(a))

[1 2 3] <class 'numpy.ndarray'>


List와 비교

In [6]:

L = [1, 2, 3]
A = np.array([1, 2, 3])

print(L)
print(A)

[1, 2, 3]
[1 2 3]


In [7]:
for item in L:
    print(item)

1
2
3


In [8]:
for item in A:
    print(item)

1
2
3


In [3]:
L.append(4)
A = np.append(A, 4)

print(L)
print(A)

[1, 2, 3, 4]
[1 2 3 4]


In [5]:
L = L + [5]
A = A + np.array([5])

print(L)
print(A)

[1, 2, 3, 4, 5, 5]
[6 7 8 9]


In [6]:
L = [1, 2, 3]
L2 = []
for item in L:
    L2.append(item*2)
print(L2)

[2, 4, 6]


In [7]:
A = np.array(L)
A2 = A*2
print(A2)

[2 4 6]


In [8]:
L*2

[1, 2, 3, 1, 2, 3]

배열

In [10]:
a = np.array([1, 2, 3])
print(a, type(a), a.ndim, a.shape, a.dtype)

[1 2 3] <class 'numpy.ndarray'> 1 (3,) int32


In [11]:
b = np.asarray(a)
print(b)

[1 2 3]


In [12]:
b[0] = 9
print(a)
print(b)

[9 2 3]
[9 2 3]


In [13]:
c = np.array(a)
print(c)

[9 2 3]


In [14]:
c[0] = 1
print(a)
print(b)
print(c)

[9 2 3]
[9 2 3]
[1 2 3]


In [16]:
a = np.zeros((3, 4))
print(a)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [17]:
b = np.ones((5, 2))
print(b)

[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


In [18]:
c = np.full((2, 3), 4)
print(c)

[[4 4 4]
 [4 4 4]]


In [20]:
d = np.empty((3, 3))
print(d)

[[8.02618970e-312 8.02618970e-312 8.02618970e-312]
 [4.94065646e-324 8.02618712e-312 8.02618966e-312]
 [0.00000000e+000 7.41098469e-323 8.02620095e-312]]


In [22]:
e = np.zeros_like(a)
f = np.ones_like(a)
g = np.full_like(a, 2)
h = np.empty_like(a)

print(e)
print(f)
print(g)
print(h)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[2. 2. 2. 2.]
 [2. 2. 2. 2.]
 [2. 2. 2. 2.]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [23]:
i = np.eye(3)
j = np.identity(3)
print(i)
print(j)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [24]:
k = np.arange(10)
print(k)

[0 1 2 3 4 5 6 7 8 9]


In [28]:
k1 = np.arange(10, 0, -1)
print(k1)

[10  9  8  7  6  5  4  3  2  1]


In [25]:
# uniform distribution
i = np.random.rand(2, 2)
print(i)

[[0.99806731 0.28163324]
 [0.78404091 0.43941305]]


In [26]:
# normal distribution
m = np.random.rand(2, 2)
print(m)

[[0.83346551 0.81833951]
 [0.30410556 0.12998952]]


배열의 dtype

In [31]:
a = np.array([1, 2, 3])
b = np.array([1, 2, 3], dtype=np.int32)
c = np.array([1, 2, 3], dtype=float)

print(a.dtype, b.dtype, c.dtype)

int32 int32 float64


In [32]:
d= np.array([1, 2, 3], dtype='i1')
e= np.array([1, 2, 3], dtype='i2')
f= np.array([1, 2, 3], dtype='i4')
g= np.array([1, 2, 3], dtype='i8')

print(d.dtype, e.dtype, f.dtype, g.dtype)

int8 int16 int32 int64


In [38]:
h = np.array([1, 2, 3], dtype='f2')
i = np.array([1, 2, 3], dtype='f4')
j = np.array([1, 2, 3], dtype='f8')
k = np.array([1, 2, 3], dtype='f8')

print(h.dtype, i.dtype, j.dtype, k.dtype)

float16 float32 float64 float64


In [10]:
h = np.array([1, 2, 3], dtype='f2')
i = np.array([1, 2, 3], dtype='f')
j = np.array([1, 2, 3], dtype='d')
k = np.array([1, 2, 3], dtype='g')

print(h.dtype, i.dtype, j.dtype, k.dtype)

float16 float32 float64 float64


In [11]:
i = i.astype(np.int32)
print(i.dtype)

int32


In [12]:
j = j.astype(i.dtype)
print(j.dtype)

int32


배열의 indexing(색인)과 slicing(슬라이싱)

indexing, slicing 기본

In [13]:
a = np.arange(10)
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [14]:
#indexing
print(a[5])

5


In [15]:
#slicing
print(a[5:8])

[5 6 7]


In [16]:
print(a[-1])

9


In [17]:
print(a[7:-1])

[7 8]


In [18]:
# index 5 ~ 8을 10으로 변경
a[5:8] = 10
print(a)

[ 0  1  2  3  4 10 10 10  8  9]


indexing과 slicing의 차이

indexing을 사용하면 항상 차원이 감소. 반면에 slicing을 사용하면 차원 유지

In [19]:
b = np.arange(1, 13)
b = b.reshape(3, 4)
print(b)
print(b.shape)
print(b.ndim)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
(3, 4)
2


In [20]:
indexing = b[1]
slicing = b[1:2]
print(indexing, indexing.shape, indexing.ndim)
print(slicing, slicing.shape, slicing.ndim)

[5 6 7 8] (4,) 1
[[5 6 7 8]] (1, 4) 2


이것은 indexing과 slicing을 함께 사용할 때도 마찬가지입니다. 
indexing의 개수 만큼 차원이 감소

In [21]:
b = b.reshape(3, 4)
print(b)
print(b.shape)
print(b.dtype)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
(3, 4)
int32


In [22]:
row_r1 = b[1, :]
row_r2 = b[1:2, :]

print(row_r1, row_r1.shape, row_r1.ndim)
print(row_r2, row_r2.shape, row_r2.ndim)

[5 6 7 8] (4,) 1
[[5 6 7 8]] (1, 4) 2


slicing example

In [23]:
c = np.arange(24).reshape(2, 3, 4)
print(c)
print(c.shape)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
(2, 3, 4)


In [24]:
# 표현법은 다르지만 결과값은 같음
print(c[:, :, :1])
print(c[...,:1])

[[[ 0]
  [ 4]
  [ 8]]

 [[12]
  [16]
  [20]]]
[[[ 0]
  [ 4]
  [ 8]]

 [[12]
  [16]
  [20]]]


In [25]:
print(c[0:1])
print(c[0::-1])

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]]
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]]


boolean indexing

In [26]:
print(c)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [27]:
# c가 10을 넘으면 True로 반환
bool_idx = (c > 10)
print(bool_idx)

[[[False False False False]
  [False False False False]
  [False False False  True]]

 [[ True  True  True  True]
  [ True  True  True  True]
  [ True  True  True  True]]]


In [28]:
# c에서 10초과 하는 값을 배열로 저장
print(c[bool_idx])

[11 12 13 14 15 16 17 18 19 20 21 22 23]


In [29]:
# c가 10보다 크면 -1로 변경
c[c>10] = -1
print(c)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 -1]]

 [[-1 -1 -1 -1]
  [-1 -1 -1 -1]
  [-1 -1 -1 -1]]]


fancy indexing

In [30]:
d = np.arange(8).reshape(8, -1)
print(d, d.shape)

[[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]] (8, 1)


In [31]:
d = np.hstack((d, d, d, d))
print(d, d.shape)

[[0 0 0 0]
 [1 1 1 1]
 [2 2 2 2]
 [3 3 3 3]
 [4 4 4 4]
 [5 5 5 5]
 [6 6 6 6]
 [7 7 7 7]] (8, 4)


In [32]:
# 배열 d에서 3, 5, 1, 0째 순으로 배열
print(d[[3, 5, 1, 0]])

[[3 3 3 3]
 [5 5 5 5]
 [1 1 1 1]
 [0 0 0 0]]


In [33]:
# 배열 d에서 역방향으로 
print(d[[-3, -5, -7]])

[[5 5 5 5]
 [3 3 3 3]
 [1 1 1 1]]


In [34]:
e = np.arange(32).reshape(8, 4)
print(e, e.shape)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]] (8, 4)


In [35]:
# 배열 c에서 (1, 0), (5, 3), (7, 1), (2, 2)값을 가져옴
print(e[[1, 5, 7, 2], [0, 3, 1, 2]])

[ 4 23 29 10]


In [36]:
# (1, 0), (1, 3), (1, 1), (1, 2)순으로 배열 생성 5, 7, 2도 동일함
print(e[[1, 5, 7, 2]][:, [0, 3, 1, 2]])

[[ 4  7  5  6]
 [20 23 21 22]
 [28 31 29 30]
 [ 8 11  9 10]]


Transpose

In [37]:
f = np.arange(16).reshape(2, 2, 4)
print(f, f.shape)

[[[ 0  1  2  3]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [12 13 14 15]]] (2, 2, 4)


In [38]:
print(f.transpose(1, 0, 2))

[[[ 0  1  2  3]
  [ 8  9 10 11]]

 [[ 4  5  6  7]
  [12 13 14 15]]]


In [39]:
print(f.swapaxes(0, 1)) 

[[[ 0  1  2  3]
  [ 8  9 10 11]]

 [[ 4  5  6  7]
  [12 13 14 15]]]


Numpy 연산

In [3]:
x = np.array([[1, 2], [3, 4]], dtype=np.float64)
y = np.array([[5, 6], [7, 8]], dtype=np.float64)
print(x)
print(y)

[[1. 2.]
 [3. 4.]]
[[5. 6.]
 [7. 8.]]


In [4]:
print(x+y)
print(np.add(x, y))

[[ 6.  8.]
 [10. 12.]]
[[ 6.  8.]
 [10. 12.]]


In [5]:
print(x-y)
print(np.subtract(x, y))

[[-4. -4.]
 [-4. -4.]]
[[-4. -4.]
 [-4. -4.]]


In [6]:
print(x*y)
print(np.multiply(x, y))

[[ 5. 12.]
 [21. 32.]]
[[ 5. 12.]
 [21. 32.]]


In [7]:
print(x / y)
print(np.divide(x, y))

[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]


In [8]:
print(x@y)
print(np.matmul(x, y))

[[19. 22.]
 [43. 50.]]
[[19. 22.]
 [43. 50.]]


In [10]:
z =np.arange(1, 11).reshape(2, 5)
print(z)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [11]:
print(np.sum(z))

55


In [13]:
sum1 = np.sum(z, axis=0)
sum2 = np.sum(z, axis=1)
sum3 = np.sum(z, axis= -1)
print(sum1, sum1.shape)
print(sum2, sum2.shape)
print(sum3, sum3.shape)

[ 7  9 11 13 15] (5,)
[15 40] (2,)
[15 40] (2,)


In [14]:
print(z[0,:] + z[1,:])
print(z[:, 0] + z[:, 1] + z[:, 2] + z[:, 3] + z[:, 4])

[ 7  9 11 13 15]
[15 40]


Broadcasting

In [15]:
x = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])
y = np.array([1, 0, 2])

In [16]:
print(x, x.shape)
print(y, y.shape)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]] (4, 3)
[1 0 2] (3,)


In [17]:
# [[1, 2, 3] + [1, 0, 2], [4, 5, 6] + [1, 0, 2], [7, 8, 9]...]
z = x + y
print(z, z.shape)

[[ 2  2  5]
 [ 5  5  8]
 [ 8  8 11]
 [11 11 14]] (4, 3)


In [19]:
x = np.array([1, 2, 3]).reshape(1, 3)
y = np.array([4, 5]).reshape(1, 2)
print(x, x.shape)
print(y, y.shape)

[[1 2 3]] (1, 3)
[[4 5]] (1, 2)


In [20]:
# broadcasting 조건에 맞지 않음
print(x+ y)

ValueError: operands could not be broadcast together with shapes (1,3) (1,2) 

In [21]:
y = y.swapaxes(0, 1)
print(y, y.shape)

[[4]
 [5]] (2, 1)


In [22]:
# broadcasting 발생
print(x + y)

[[5 6 7]
 [6 7 8]]


shape 변경

In [23]:
a = np.arange(24).reshape(2, 3, 4)
print(a, a.shape)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]] (2, 3, 4)


In [24]:
a = a.reshape(4, -1)
print(a, a.shape)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]] (4, 6)


In [25]:
a = a[..., np.newaxis]
print(a, a.shape)

[[[ 0]
  [ 1]
  [ 2]
  [ 3]
  [ 4]
  [ 5]]

 [[ 6]
  [ 7]
  [ 8]
  [ 9]
  [10]
  [11]]

 [[12]
  [13]
  [14]
  [15]
  [16]
  [17]]

 [[18]
  [19]
  [20]
  [21]
  [22]
  [23]]] (4, 6, 1)


In [26]:
a = a.reshape(4, 6)
a = np.expand_dims(a, axis=0)
print(a, a.shape)

[[[ 0  1  2  3  4  5]
  [ 6  7  8  9 10 11]
  [12 13 14 15 16 17]
  [18 19 20 21 22 23]]] (1, 4, 6)


In [27]:
b = a.copy()
print(b, b.shape)

[[[ 0  1  2  3  4  5]
  [ 6  7  8  9 10 11]
  [12 13 14 15 16 17]
  [18 19 20 21 22 23]]] (1, 4, 6)


In [31]:
c = np.concatenate((a, b), axis=1)
print(c)

[[[ 0  1  2  3  4  5]
  [ 6  7  8  9 10 11]
  [12 13 14 15 16 17]
  [18 19 20 21 22 23]
  [ 0  1  2  3  4  5]
  [ 6  7  8  9 10 11]
  [12 13 14 15 16 17]
  [18 19 20 21 22 23]]]


In [29]:
c = np.concatenate((a, b), axis=0)
print(c)

[[[ 0  1  2  3  4  5]
  [ 6  7  8  9 10 11]
  [12 13 14 15 16 17]
  [18 19 20 21 22 23]]

 [[ 0  1  2  3  4  5]
  [ 6  7  8  9 10 11]
  [12 13 14 15 16 17]
  [18 19 20 21 22 23]]]


In [32]:
c = np.concatenate((a, b), axis=-1)
print(c)

[[[ 0  1  2  3  4  5  0  1  2  3  4  5]
  [ 6  7  8  9 10 11  6  7  8  9 10 11]
  [12 13 14 15 16 17 12 13 14 15 16 17]
  [18 19 20 21 22 23 18 19 20 21 22 23]]]


In [33]:
d = np.stack((a, b), axis=1)
print(d)

[[[[ 0  1  2  3  4  5]
   [ 6  7  8  9 10 11]
   [12 13 14 15 16 17]
   [18 19 20 21 22 23]]

  [[ 0  1  2  3  4  5]
   [ 6  7  8  9 10 11]
   [12 13 14 15 16 17]
   [18 19 20 21 22 23]]]]


In [34]:
d = np.stack((a, b), axis=0)
print(d)

[[[[ 0  1  2  3  4  5]
   [ 6  7  8  9 10 11]
   [12 13 14 15 16 17]
   [18 19 20 21 22 23]]]


 [[[ 0  1  2  3  4  5]
   [ 6  7  8  9 10 11]
   [12 13 14 15 16 17]
   [18 19 20 21 22 23]]]]


In [36]:
d =np.stack((a, b), axis=-1)
print(d)

[[[[ 0  0]
   [ 1  1]
   [ 2  2]
   [ 3  3]
   [ 4  4]
   [ 5  5]]

  [[ 6  6]
   [ 7  7]
   [ 8  8]
   [ 9  9]
   [10 10]
   [11 11]]

  [[12 12]
   [13 13]
   [14 14]
   [15 15]
   [16 16]
   [17 17]]

  [[18 18]
   [19 19]
   [20 20]
   [21 21]
   [22 22]
   [23 23]]]]
