Numpy

In [ ]:
import numpy as np

Numpy ndarray

In [9]:
a = np.array([1, 2, 3])
print(a, type(a))

[1 2 3] <class 'numpy.ndarray'>


List와 비교

In [2]:

L = [1, 2, 3]
A = np.array([1, 2, 3])

print(L)
print(A)

[1, 2, 3]
[1 2 3]


In [3]:
L.append(4)
A = np.append(A, 4)

print(L)
print(A)

[1, 2, 3, 4]
[1 2 3 4]


In [5]:
L = L + [5]
A = A + np.array([5])

print(L)
print(A)

[1, 2, 3, 4, 5, 5]
[6 7 8 9]


In [6]:
L = [1, 2, 3]
L2 = []
for item in L:
    L2.append(item*2)
print(L2)

[2, 4, 6]


In [7]:
A = np.array(L)
A2 = A*2
print(A2)

[2 4 6]


In [8]:
L*2

[1, 2, 3, 1, 2, 3]

배열

In [10]:
a = np.array([1, 2, 3])
print(a, type(a), a.ndim, a.shape, a.dtype)

[1 2 3] <class 'numpy.ndarray'> 1 (3,) int32


In [11]:
b = np.asarray(a)
print(b)

[1 2 3]


In [12]:
b[0] = 9
print(a)
print(b)

[9 2 3]
[9 2 3]


In [13]:
c = np.array(a)
print(c)

[9 2 3]


In [14]:
c[0] = 1
print(a)
print(b)
print(c)

[9 2 3]
[9 2 3]
[1 2 3]


In [16]:
a = np.zeros((3, 4))
print(a)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [17]:
b = np.ones((5, 2))
print(b)

[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


In [18]:
c = np.full((2, 3), 4)
print(c)

[[4 4 4]
 [4 4 4]]


In [20]:
d = np.empty((3, 3))
print(d)

[[8.02618970e-312 8.02618970e-312 8.02618970e-312]
 [4.94065646e-324 8.02618712e-312 8.02618966e-312]
 [0.00000000e+000 7.41098469e-323 8.02620095e-312]]


In [22]:
e = np.zeros_like(a)
f = np.ones_like(a)
g = np.full_like(a, 2)
h = np.empty_like(a)

print(e)
print(f)
print(g)
print(h)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[2. 2. 2. 2.]
 [2. 2. 2. 2.]
 [2. 2. 2. 2.]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [23]:
i = np.eye(3)
j = np.identity(3)
print(i)
print(j)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [24]:
k = np.arange(10)
print(k)

[0 1 2 3 4 5 6 7 8 9]


In [28]:
k1 = np.arange(10, 0, -1)
print(k1)

[10  9  8  7  6  5  4  3  2  1]


In [25]:
# uniform distribution
i = np.random.rand(2, 2)
print(i)

[[0.99806731 0.28163324]
 [0.78404091 0.43941305]]


In [26]:
# normal distribution
m = np.random.rand(2, 2)
print(m)

[[0.83346551 0.81833951]
 [0.30410556 0.12998952]]


배열의 dtype

In [31]:
a = np.array([1, 2, 3])
b = np.array([1, 2, 3], dtype=np.int32)
c = np.array([1, 2, 3], dtype=float)

print(a.dtype, b.dtype, c.dtype)

int32 int32 float64


In [32]:
d= np.array([1, 2, 3], dtype='i1')
e= np.array([1, 2, 3], dtype='i2')
f= np.array([1, 2, 3], dtype='i4')
g= np.array([1, 2, 3], dtype='i8')

print(d.dtype, e.dtype, f.dtype, g.dtype)

int8 int16 int32 int64


In [38]:
h = np.array([1, 2, 3], dtype='f2')
i = np.array([1, 2, 3], dtype='f4')
j = np.array([1, 2, 3], dtype='f8')
k = np.array([1, 2, 3], dtype='f8')

print(h.dtype, i.dtype, j.dtype, k.dtype)

float16 float32 float64 float64


배열의 indexing(색인)과 slicing(슬라이싱)