5-1: Conv Layers

Code.5-1-1: Shape of Conv Layers

In [16]:
import tensorflow as tf

from tensorflow.keras.layers import Conv2D

N, n_H, n_W, n_C = 32, 28, 28, 5
n_filters = 10
k_size = 3

images = tf.random.uniform(minval=0, maxval=1, shape=(N, n_H, n_W, n_C))

conv = Conv2D(filters=n_filters, kernel_size=k_size)

y = conv(images)

W, B = conv.get_weights()

print(images.shape)
print(W.shape)
print(B.shape)
print(y.shape)

(1, 5, 5, 1)
(3, 3, 1, 10)
(10,)
(1, 3, 3, 10)


Code.5-1-2: Correlation Calculation

In [21]:
import numpy as np
import tensorflow as tf

from tensorflow.keras.layers import Conv2D

N, n_H, n_W, n_C = 1, 5, 5, 1
n_filters = 1
k_size = 3

images = tf.random.uniform(minval=0, maxval=1, shape=(N, n_H, n_W, n_C))

conv = Conv2D(filters=n_filters, kernel_size=k_size)

y = conv(images)
print("Y(Tensorflow): \n", y.numpy().squeeze())
W, B = conv.get_weights()


#### Y_manual
image = images.numpy().squeeze()
W = W.squeeze()

y_man = np.zeros(shape=(n_H-k_size+1, n_W-k_size+1))
for i in range(n_H-k_size+1):
    for j in range(n_W-k_size+1):
      window = image[i:i+k_size, j:j+k_size]
      y_man[i, j] = np.sum(window * W) + B

print("Y(Manual): \n", y_man)


Y(Tensorflow): 
 [[-0.5734839  -0.02098331 -0.16955844]
 [-0.4577363  -0.08154676 -0.0783601 ]
 [-0.1582823  -0.3774488  -0.33509964]]
Y(Manual): 
 [[-0.57348394 -0.02098331 -0.16955844]
 [-0.45773631 -0.08154676 -0.07836007]
 [-0.15828231 -0.37744877 -0.33509964]]


Code.5-1-3: Correlation with n-channel

In [27]:
import numpy as np
import tensorflow as tf

from tensorflow.keras.layers import Conv2D

N, n_H, n_W, n_C = 1, 5, 5, 3
n_filters = 1
k_size = 3

images = tf.random.uniform(minval=0, maxval=1, shape=(N, n_H, n_W, n_C))

conv = Conv2D(filters=n_filters, kernel_size=k_size)

y = conv(images)
print("Y(Tensorflow): \n", y.numpy().squeeze())
W, B = conv.get_weights()


#### Y_manual

images = images.numpy().squeeze()
W = W.squeeze()
print(images.shape)
print(W.shape)
y_man = np.zeros(shape=(n_H-k_size+1, n_W-k_size+1))
for i in range(n_H-k_size+1):
    for j in range(n_W-k_size+1):
       window = image[i: i+k_size, j : j+k_size, :]
       y_man[i, j] = np.sum(window * W) + B

print("Y(Manual): \n", y_man)

Y(Tensorflow): 
 [[-0.82729334 -1.1270132  -1.133589  ]
 [-1.1337098  -1.1980127  -1.3054283 ]
 [-1.0531439   0.12001917 -1.1948135 ]]
(5, 5, 3)
(3, 3, 3)
Y(Manual): 
 [[-0.23680902 -0.92117411 -0.78851318]
 [-1.02601635 -1.29761326 -1.32911587]
 [-1.55491352 -0.85642511 -1.0152576 ]]


5-2: Conv Layer with Filters

Code.5-2-1: Shapes with Filters

In [2]:
import tensorflow as tf

from tensorflow.keras.layers import Conv2D

N, n_H, n_W, n_C = 1, 28, 28, 3
n_filters = 5
k_size = 3

images = tf.random.uniform(minval=0, maxval=1, shape=(N, n_H,n_W, n_C))

conv = Conv2D(filters=n_filters, kernel_size=k_size)

Y = conv(images)

W, B = conv.get_weights()

print("Input Image: {}".format(images.shape))
print("W/B: {} / {}".format(W.shape, B.shape))
print("Output Image: {}".format(Y.shape))


Input Image: (1, 28, 28, 3)
W/B: (3, 3, 3, 5) / (5,)
Output Image: (1, 26, 26, 5)


Code.5-2-2: Computation with Filters

In [35]:
import numpy as np
import tensorflow as tf

from tensorflow.keras.layers import Conv2D

N, n_H, n_W, n_C = 1, 5, 5, 3
n_filters = 3
k_size = 4

images = tf.random.uniform(minval=0, maxval=1, shape=(N, n_H,n_W, n_C))

# forward propagation TensorFlow
conv = Conv2D(filters=n_filters, kernel_size=k_size)
Y = conv(images)
Y=np.transpose(Y.numpy().squeeze(), (2, 0, 1))
print("Y(Tensorflow): \n", Y)

W, B = conv.get_weights()
# Forward Propagation Manual
images = images.numpy().squeeze()

Y_man = np.zeros(shape=(n_H-k_size+1, n_W-k_size+1, n_filters))

for c in range(n_filters):
    c_W = W[:, :, :, c]
    c_B = B[c]

    for h in range(n_H- k_size+1):
        for j in range(n_W -k_size +1):
            window = images[h:h+k_size, j:j+k_size, :]
            conv = np.sum(window * c_W) + c_B

            Y_man[h, j, c] = conv

print("Y(Manual): \n", np.transpose(Y_man, (2, 0, 1)))


Y(Tensorflow): 
 [[[-0.20806664  0.02978007]
  [-0.13757414 -0.31216973]]

 [[ 0.56339675  0.99136883]
  [ 1.1394992   0.37163904]]

 [[ 0.7371725   0.15534487]
  [-0.02891804  0.59019226]]]
Y(Manual): 
 [[[-0.2080667   0.02978   ]
  [-0.13757414 -0.31216973]]

 [[ 0.56339669  0.99136889]
  [ 1.13949919  0.37163904]]

 [[ 0.73717248  0.15534478]
  [-0.02891807  0.59019226]]]


In [19]:
import numpy as np

images = np.random.randint(low=0, high=10, size=(2, 3, 4))
for c in range(4):
    print(images[:, :, c])

print('\n')
images = np.transpose(images, (2, 0, 1))
for c in range(4):
    print(images[c,:, : ])

[[3 7 1]
 [7 1 1]]
[[7 7 8]
 [5 5 1]]
[[0 5 3]
 [8 7 8]]
[[9 1 7]
 [5 2 6]]


[[3 7 1]
 [7 1 1]]
[[7 7 8]
 [5 5 1]]
[[0 5 3]
 [8 7 8]]
[[9 1 7]
 [5 2 6]]


5-3: Conv Layer with Activation Functions

Code.5-3-1: Conv Layers with Activation Functions

In [38]:
import numpy as np
import tensorflow as tf

from tensorflow.keras.layers import Conv2D

N, n_H, n_W, n_C = 1, 5, 5, 3
n_filters = 3
k_size = 4

images = tf.random.uniform(minval=0, maxval=1, shape=(N, n_H,n_W, n_C))

# forward propagation TensorFlow
conv = Conv2D(filters=n_filters, kernel_size=k_size, activation='sigmoid')
Y = conv(images)
Y=np.transpose(Y.numpy().squeeze(), (2, 0, 1))
print("Y(Tensorflow): \n", Y)

W, B = conv.get_weights()
# Forward Propagation Manual
images = images.numpy().squeeze()

Y_man = np.zeros(shape=(n_H-k_size+1, n_W-k_size+1, n_filters))

for c in range(n_filters):
    c_W = W[:, :, :, c]
    c_B = B[c]

    for h in range(n_H- k_size+1):
        for j in range(n_W -k_size +1):
            window = images[h:h+k_size, j:j+k_size, :]
            conv = np.sum(window * c_W) + c_B
            conv = 1/(1+np.exp(-conv))

            Y_man[h, j, c] = conv

print("Y(Manual): \n", np.transpose(Y_man, (2, 0, 1)))

Y(Tensorflow): 
 [[[0.30625996 0.23535341]
  [0.29678443 0.30722627]]

 [[0.28173614 0.3036828 ]
  [0.36261952 0.3900584 ]]

 [[0.42864    0.52155966]
  [0.5875762  0.4721069 ]]]
Y(Manual): 
 [[[0.30625994 0.23535344]
  [0.29678444 0.30722629]]

 [[0.28173618 0.30368277]
  [0.36261952 0.39005838]]

 [[0.42864005 0.5215597 ]
  [0.5875762  0.47210688]]]


5-4: Models with Conv Layers

Code.5-4-1: Models with Sequential Method

In [46]:
import tensorflow as tf

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv2D

n_neuron = [10, 20, 30]

model = Sequential()

# [26,26,10]
model.add(Conv2D(filters=n_neuron[0], kernel_size=3, activation='sigmoid'))
# [24,24,20]
model.add(Conv2D(filters=n_neuron[1], kernel_size=3,activation='relu'))
# [22,22,10]
model.add(Conv2D(filters=n_neuron[2], kernel_size=3,activation='relu'))

x = tf.random.normal(shape=(32, 28, 28, 3))
prediction = model(x)


print("Input: {}".format(x.shape))
print("Output: {}".format(prediction.shape))

for layer in model.layers:
    W, B = layer.get_weights()
    print(W.shape, B.shape)

trainable_variables = model.trainable_variables
for train_var in trainable_variables:
    print(train_var.shape)


Input: (32, 28, 28, 3)
Output: (32, 22, 22, 30)
(3, 3, 3, 10) (10,)
(3, 3, 10, 20) (20,)
(3, 3, 20, 30) (30,)
(3, 3, 3, 10)
(10,)
(3, 3, 10, 20)
(20,)
(3, 3, 20, 30)
(30,)


Code.5-4-2: Models with Model Sub-classing

In [55]:
import tensorflow as tf

from tensorflow.keras.models import Model
from tensorflow.keras.layers import Conv2D

n_neurons = [10, 20, 30]

# layer가 비슷할 때
class TestModel(Model):
    def __init__(self):
        super(TestModel, self).__init__()
        global n_neurons

        self.conv_layers = []
        for n_neuron in n_neurons:
            self.conv_layers.append(Conv2D(filters=n_neuron, kernel_size=3, activation='relu'))

    def call(self, x):
        # print("Input: {}",x.shape)

        # print("========== Conv Layers ==========")
        for conv_layer in self.conv_layers:
            x = conv_layer(x)
            W, B = conv_layer.get_weights()
            # print("W/B: {} / {}".format(W.shape, B.shape))
            # print("X: {}\n".format(x.shape))
        return(x)
        
model = TestModel()
x = tf.random.normal(shape=(32, 28, 28,3))
prediction = model(x)

# layer가 조금씩 다를 때
class TestModel(Model):
    def __init__(self):
        super(TestModel, self).__init__()
        global n_neurons

        self.conv_layers = []
        for n_neuron in n_neurons:
            self.conv_layers.append(Conv2D(filters=n_neuron, kernel_size=3, activation='relu'))
        
        self.conv1 = Conv2D(filters=n_neuron[0], kernel_size=3, activation='relu')
        self.conv2 = Conv2D(filters=n_neuron[0], kernel_size=3, activation='relu')
        self.conv3 = Conv2D(filters=n_neuron[0], kernel_size=3, activation='relu')
    def call(self, x):
        x = self.conv1(x)
        x = self.conv2(x)
        x = self.conv3(x)

        return(x)


Input: {} (32, 28, 28, 3)
========== Conv Layers ==========
W/B: (3, 3, 3, 10) / (10,)
X: (32, 26, 26, 10)

W/B: (3, 3, 10, 20) / (20,)
X: (32, 24, 24, 20)

W/B: (3, 3, 20, 30) / (30,)
X: (32, 22, 22, 30)

