6-1: Max/Avg Pooling

Code.6-1-1: Max Pooling

In [7]:
import numpy as np
import tensorflow as tf

from tensorflow.keras.layers import MaxPooling1D

L, f, s =10, 2, 1

x= tf.random.normal(shape=(1, L,1))
pool_max = MaxPooling1D(pool_size=f, strides=s)
pooled_max = pool_max(x)

print("x: {}\n{}".format(x.shape, x.numpy().flatten()))
print("pooled_max(Tensorflow): {}\n{}".format(pooled_max.shape, pooled_max.numpy().flatten()))


# Manual
x = x.numpy().flatten()
pooled_max_man = np.zeros((L -f + 1,))
for i in range(L-f + 1):
    window = x[i:i+f]
    pooled_max_man[i] = np.max(window)

print("pooled_max(Manual): {}\n{}".format(pooled_max_man.shape, pooled_max_man))



x: (1, 10, 1)
[-0.99408567 -0.36502454 -0.51029503 -0.25843957 -1.1751118  -2.3684921
  0.00828075  1.6627219   0.45045993 -1.63395   ]
pooled_max(Tensorflow): (1, 9, 1)
[-0.36502454 -0.36502454 -0.25843957 -0.25843957 -1.1751118   0.00828075
  1.6627219   1.6627219   0.45045993]
pooled_max(Manual): (9,)
[-0.36502454 -0.36502454 -0.25843957 -0.25843957 -1.17511177  0.00828075
  1.66272187  1.66272187  0.45045993]


Code.6-1-2: Average Pooling

In [11]:
import numpy as np
import tensorflow as tf

from tensorflow.keras.layers import AveragePooling1D

L, f, s =10, 2, 1

x= tf.random.normal(shape=(1, L,1))
pool_avg = AveragePooling1D(pool_size=f, strides=s)
pooled_avg = pool_avg(x)

print("x: {}\n{}".format(x.shape, x.numpy().flatten()))
print("pooled_avg(Tensorflow): {}\n{}".format(pooled_avg.shape, pooled_avg.numpy().flatten()))

# Manual

x = x.numpy().flatten()
pooled_avg_man = np.zeros((L -f + 1,))
for i in range(L-f + 1):
    window = x[i:i+f]
    pooled_avg_man[i] = np.mean(window)

print("pooled_avg_mean(Manual): {}\n{}".format(pooled_avg_man.shape, pooled_avg_man))


x: (1, 10, 1)
[-0.84000224 -0.01348868  0.36423856 -0.1766504   0.21998553  0.0182764
  0.8590493  -0.70815986  0.6717431  -0.8773922 ]
pooled_avg(Tensorflow): (1, 9, 1)
[-0.42674544  0.17537494  0.09379408  0.02166756  0.11913096  0.43866286
  0.07544473 -0.01820838 -0.10282454]
pooled_avg_mean(Manual): (9,)
[-0.42674544  0.17537494  0.09379408  0.02166756  0.11913096  0.43866286
  0.07544473 -0.01820838 -0.10282454]


6-2: 2D Max/Avg Pooling

Code.6-2-1: 2D Max Pooling

In [23]:
import numpy as np
import tensorflow as tf

from tensorflow.keras.layers import MaxPooling2D

N, n_H, n_W, n_C = 1, 5, 5, 1
f, s = 2, 1

x= tf.random.normal(shape=(N, n_H, n_W, n_C))
pool_max = MaxPooling2D(pool_size=f, strides=s)
pooled_max = pool_max(x)

print("x: {}\n{}".format(x.shape, x.numpy().squeeze()))
print("pooled_max(Tensorflow): {}\n{}".format(pooled_max.shape, pooled_max.numpy().squeeze()))

# Manual
x = x.numpy().squeeze()
pooled_max_man = np.zeros(shape=(n_H - f + 1, n_W - f + 1))
for i in range(n_H - f + 1):
    for j in range(n_W - f + 1):
        window = x[i : i+f, j : j+f]
        pooled_max_man[i, j] = np.max(window)

print("pooled max(Manual): {}\n{}".format(pooled_max_man.shape,
                                          pooled_max_man))


x: (1, 5, 5, 1)
[[ 0.47351816  1.0318073  -1.3997251   0.52663445 -0.3926086 ]
 [ 0.6849758  -0.34114856  0.20860851 -0.37414783 -0.14817508]
 [ 0.59603035  0.6434641   0.43336403 -1.221865   -0.38886914]
 [ 1.222959    0.57558304 -0.6374326  -0.19814833 -0.40540224]
 [ 1.2700887  -2.0693772   1.144808    0.03701729  1.1116526 ]]
pooled_max(Tensorflow): (1, 4, 4, 1)
[[ 1.0318073   1.0318073   0.52663445  0.52663445]
 [ 0.6849758   0.6434641   0.43336403 -0.14817508]
 [ 1.222959    0.6434641   0.43336403 -0.19814833]
 [ 1.2700887   1.144808    1.144808    1.1116526 ]]
pooled max(Manual): (4, 4)
[[ 1.0318073   1.0318073   0.52663445  0.52663445]
 [ 0.6849758   0.64346409  0.43336403 -0.14817508]
 [ 1.22295904  0.64346409  0.43336403 -0.19814833]
 [ 1.27008867  1.14480805  1.14480805  1.11165261]]


Code.6-2-2: 2D Average Pooling

In [24]:
import numpy as np
import tensorflow as tf

from tensorflow.keras.layers import AveragePooling2D

N, n_H, n_W, n_C = 1, 5, 5, 1
f, s = 3, 1

x= tf.random.normal(shape=(N, n_H, n_W, n_C))
pool_avg = AveragePooling2D(pool_size=f, strides=s)
pooled_avg = pool_avg(x)

print("x: {}\n{}".format(x.shape, x.numpy().squeeze()))
print("pooled_avg(Tensorflow): {}\n{}".format(pooled_avg.shape, pooled_avg.numpy().squeeze()))

# Manual
x = x.numpy().squeeze()
pooled_avg_man = np.zeros(shape=(n_H - f + 1, n_W - f + 1))
for i in range(n_H - f +1):
    for j in range(n_W - f +1):
        window = x[i : i+f, j : j+f]
        pooled_avg_man[i, j] = np.mean(window)

print("pooled avg(Manual): {}\n{}".format(pooled_avg_man.shape,
                                          pooled_avg_man))

x: (1, 5, 5, 1)
[[ 0.21940939 -0.6878008  -0.06987957  0.7211153   2.03736   ]
 [-1.4991447   0.6727637   0.3663228   0.4365492   0.4713086 ]
 [ 1.0875227  -1.717605    0.04097221  0.46558893 -0.34974107]
 [-2.6727843   0.35982314 -1.0758941   1.1951046   0.09840611]
 [ 1.1594263   1.0264179   0.68314326  1.8315254   0.89402974]]
pooled_avg(Tensorflow): (1, 3, 3, 1)
[[-0.17638214  0.0253363   0.45773295]
 [-0.49311373  0.08262505  0.18317968]
 [-0.12321973  0.3121196   0.42034832]]
pooled avg(Manual): (3, 3)
[[-0.17638212  0.02533629  0.45773295]
 [-0.49311373  0.08262505  0.18317968]
 [-0.12321976  0.3121196   0.42034832]]


6-3: 3D Max/Avg Pooling

Code.6-3-1: 3D Max Pooling

In [45]:
import math
import numpy as np
import tensorflow as tf

from tensorflow.keras.layers import MaxPooling2D

N, n_H, n_W, n_C = 1, 5, 5, 3
f, s = 2, 2

x = tf.random.normal(shape=(N, n_H, n_W, n_C))


pool_max = MaxPooling2D(pool_size=f, strides=s)
pooled_max = pool_max(x)

pooled_max_t = np.transpose(pooled_max.numpy().squeeze(), (2, 0, 1))
print("pooled_max(Tensorflow): {}\n{}".format(pooled_max.shape, pooled_max_t))

# Manual
x = x.numpy().squeeze()
n_H_ = math. floor((n_H - f)/s + 1)
n_W_ = math.floor((n_W - f)/s + 1)
pooled_max_man = np.zeros(shape=(n_H_, n_W_, n_C))

for c in range(n_C):
  c_image = x[:, :, c]
  h_ = 0
  
  for h in range(0, n_H - f + 1, s):
    w_=0
    for w in range(0, n_W - f + 1 , s):
      window = c_image[h : h+f, w : w+f]
      pooled_max_man[h_, w_, c] = np.max(window)
      
      w_ +=1
    h_ +=1

pooled_max_t = np.transpose(pooled_max_man, (2, 0, 1))
print("pooled max(Manual): {}\n{}".format (pooled_max_man.shape,
                                            pooled_max_t))

pooled_max(Tensorflow): (1, 2, 2, 3)
[[[0.10830654 1.0034595 ]
  [1.1218007  0.37096536]]

 [[1.0766754  0.5331262 ]
  [0.255309   0.7513643 ]]

 [[1.1351019  0.50589055]
  [1.2281375  1.5983205 ]]]
pooled max(Manual): (2, 2, 3)
[[[0.10830654 1.00345945]
  [1.12180066 0.37096536]]

 [[1.07667542 0.53312618]
  [0.25530899 0.75136429]]

 [[1.13510191 0.50589055]
  [1.22813749 1.59832048]]]


6-4: Padding

Code.6-4-1: ZeroPadding2D Layer

In [52]:
import numpy as np
import tensorflow as tf

from tensorflow.keras.layers import ZeroPadding2D

image = tf.random.normal(shape=(1, 28, 28, 3))
print(image.shape)
# print(np.transpose(image.numpy().squeeze(), (2, 0, 1)))

zero_padding = ZeroPadding2D(padding=2)
y = zero_padding(image)
print(y.shape)
# print(np.transpose(y.numpy().squeeze(), (2, 0, 1)))

(1, 28, 28, 3)
(1, 32, 32, 3)


Code.6-4-2: Zero Padding with Conv2D Layers

In [53]:
import tensorflow as tf

from tensorflow.keras.layers import Conv2D

image = tf.random.normal(shape=(1, 28, 28, 3))
conv = Conv2D(filters=1, kernel_size=3, padding='same')
y = conv(image)
print(y.shape)

(1, 28, 28, 1)


6-5: Strides

Code.6-5-1: Strides in Conv2D Layers

In [61]:
import tensorflow as tf

from tensorflow.keras.layers import Conv2D

images = tf.random.normal(shape=(1, 28, 28, 3))
conv = Conv2D(filters=1, kernel_size=3, padding='valid', strides=2)
y = conv(images)

print(image.shape)
print(y.shape)

(1, 28, 28, 3)
(1, 13, 13, 1)


Code.6-5-2: Strides in Pooling Layers

In [62]:
import tensorflow as tf

from tensorflow.keras.layers import MaxPooling2D

images = tf.random.normal(shape=(1, 28, 28, 3))
pool = MaxPooling2D(pool_size=3, strides=2)
y = pool(images)

print(image.shape)
print(y.shape)

(1, 28, 28, 3)
(1, 13, 13, 3)
